In [17]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/data-master.csv', sep=';')
df.shape

(1641, 79)

In [4]:
selected_cols_to_analyze = ['Level of Interaction with Disaster', 'Frequency of Usage (max) (in month)', 'Usage Duration', 
                            'Number of LIK Combination', 'Number of Experience with Disaster', 'Age', 'Fishing Experience', 'Beach']

df = df[selected_cols_to_analyze]
df.columns

Index(['Level of Interaction with Disaster',
       'Frequency of Usage (max) (in month)', 'Usage Duration',
       'Number of LIK Combination', 'Number of Experience with Disaster',
       'Age', 'Fishing Experience', 'Beach'],
      dtype='str')

In [5]:
beach_map = {
    1: 'pantai lampuuk',
    2: 'pantai lhoknga',
    3: 'pantai ulee lheue',
    4: 'pantai depok',
    5: 'pantai samas',
}

df['Mapped Beach'] = df['Beach'].map(beach_map)

df.drop(columns=['Beach'], inplace=True)

print('Data cleaned')

Data cleaned

In [6]:
df_pantai_lampuuk = df[df['Mapped Beach'] == 'pantai lampuuk']
df_pantai_lhoknga = df[df['Mapped Beach'] == 'pantai lhoknga']
df_pantai_ulee_lheue = df[df['Mapped Beach'] == 'pantai ulee lheue']
df_pantai_depok = df[df['Mapped Beach'] == 'pantai depok']
df_pantai_samas = df[df['Mapped Beach'] == 'pantai samas']

# Pantai Lampuk

In [7]:
df_pantai_lampuuk.describe()

,Level of Interaction with Disaster,Frequency of Usage (max) (in month),Usage Duration,Number of LIK Combination,Number of Experience with Disaster,Age,Fishing Experience
count,426.000000,426.000000,426.000000,426.000000,426.000000,426.000000,426.000000
mean,3.802817,14.502347,14.915493,2.183099,2.267606,39.180751,15.091549
std,2.291384,9.653344,8.235784,1.005536,0.747534,9.744390,8.698807
min,0.000000,2.000000,1.000000,1.000000,1.000000,20.000000,2.000000
25%,2.000000,5.000000,8.000000,1.000000,2.000000,30.000000,8.000000
50%,4.000000,20.000000,13.500000,2.000000,2.000000,39.000000,13.000000
75%,5.000000,24.000000,20.000000,3.000000,3.000000,47.000000,21.000000
max,8.000000,32.000000,43.000000,4.000000,5.000000,62.000000,43.000000

# Pantai Lhoknga

In [8]:
df_pantai_lhoknga.describe()

,Level of Interaction with Disaster,Frequency of Usage (max) (in month),Usage Duration,Number of LIK Combination,Number of Experience with Disaster,Age,Fishing Experience
count,687.000000,687.000000,687.000000,687.000000,687.000000,687.000000,687.000000
mean,1.272198,6.275109,17.983988,2.091703,2.739447,42.742358,17.918486
std,1.784326,7.662430,8.050390,0.818181,0.960109,8.649761,8.152826
min,0.000000,1.000000,4.000000,1.000000,1.000000,26.000000,3.000000
25%,0.000000,2.000000,11.000000,1.000000,2.000000,36.000000,11.000000
50%,1.000000,3.000000,17.000000,2.000000,3.000000,42.000000,17.000000
75%,2.000000,5.000000,22.000000,3.000000,3.000000,50.000000,22.000000
max,8.000000,32.000000,38.000000,4.000000,5.000000,60.000000,38.000000

# Pantai Ulee Lheue

In [9]:
df_pantai_ulee_lheue.describe()

,Level of Interaction with Disaster,Frequency of Usage (max) (in month),Usage Duration,Number of LIK Combination,Number of Experience with Disaster,Age,Fishing Experience
count,436.000000,430.000000,436.000000,436.000000,436.000000,436.000000,436.000000
mean,3.594037,4.446512,19.752294,1.529817,2.922018,48.288991,21.442661
std,1.827720,5.953642,4.844537,0.633568,0.634902,5.949903,4.958579
min,0.000000,1.000000,5.000000,1.000000,1.000000,27.000000,5.000000
25%,2.000000,2.000000,17.000000,1.000000,3.000000,45.000000,18.000000
50%,4.000000,3.000000,20.000000,1.000000,3.000000,49.000000,23.500000
75%,5.000000,4.000000,23.000000,2.000000,3.000000,53.000000,25.000000
max,8.000000,30.000000,36.000000,4.000000,4.000000,60.000000,35.000000

In [27]:
pantai_ulee_lheue_characteristics_input = {
    'Level of Interaction with Disaster': 3.59,
    'Age': 48.28,
    'Usage Duration': 19.75,
    'Frequency of Usage (min) (in month)': 4.27,
    'Fishing Experience': 21.44
}

# Pantai Depok

In [10]:
df_pantai_depok.describe()

,Level of Interaction with Disaster,Frequency of Usage (max) (in month),Usage Duration,Number of LIK Combination,Number of Experience with Disaster,Age,Fishing Experience
count,60.000000,59.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,4.433333,2.627119,12.516667,1.100000,1.533333,41.266667,15.583333
std,2.374773,1.388354,5.273829,0.302532,0.623459,7.668705,5.929792
min,2.000000,1.000000,2.000000,1.000000,1.000000,22.000000,2.000000
25%,3.000000,1.000000,9.500000,1.000000,1.000000,38.000000,10.000000
50%,4.000000,2.000000,15.000000,1.000000,1.000000,43.000000,15.000000
75%,5.000000,4.000000,15.000000,1.000000,2.000000,46.000000,20.000000
max,15.000000,5.000000,20.000000,2.000000,3.000000,60.000000,25.000000

# Pantai Samas

In [11]:
df_pantai_samas.describe()

,Level of Interaction with Disaster,Frequency of Usage (max) (in month),Usage Duration,Number of LIK Combination,Number of Experience with Disaster,Age,Fishing Experience
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000
mean,2.125000,2.593750,4.968750,1.625000,1.500000,28.937500,6.343750
std,0.941858,1.364513,2.520681,0.793116,0.762001,5.913012,3.307951
min,1.000000,1.000000,1.000000,1.000000,1.000000,19.000000,1.000000
25%,1.000000,1.000000,3.000000,1.000000,1.000000,24.000000,5.000000
50%,2.000000,2.000000,5.000000,1.000000,1.000000,28.000000,6.000000
75%,3.000000,4.000000,7.000000,2.000000,2.000000,32.000000,7.000000
max,5.000000,5.000000,10.000000,3.000000,3.000000,40.000000,15.000000

In [15]:
# Further analysis

df_grouped = df.groupby('Mapped Beach').mean()

In [21]:
rules_map = {
    'level_of_interaction_with_disaster': 1.50,
    'frequency_of_usage': 5.50,
    'usage_duration': 17.50,
    'number_of_lik_combination': 1.50,
    'number_of_experience_with_disaster': 1.50,
}

df_grouped['Level of Interaction with Disaster Status'] = np.where(df_grouped['Level of Interaction with Disaster'] > 1.50, 'Safe', 'Unsafe')
df_grouped['Frequency of Usage Status'] = np.where(df_grouped['Frequency of Usage (max) (in month)'] > 5.50, 'Safe', 'Unsafe')
df_grouped['Usage Duration Status'] = np.where(df_grouped['Usage Duration'] > 17.50, 'Safe', 'Unsafe')
df_grouped['Number of LIK Combination Status'] = np.where(df_grouped['Number of LIK Combination'] > 1.50, 'Safe', 'Unsafe')
df_grouped['Number of Experience with Disaster Status'] = np.where(df_grouped['Number of Experience with Disaster'] > 1.50, 'Safe', 'Unsafe'))

In [22]:
df_grouped.head()

,Level of Interaction with Disaster,Frequency of Usage (max) (in month),Usage Duration,Number of LIK Combination,Number of Experience with Disaster,Age,Fishing Experience,Level of Interaction with Disaster Status,Frequency of Usage Status,Usage Duration Status,Number of LIK Combination Status,Number of Experience with Disaster Status
Mapped Beach,,,,,,,,,,,,
pantai depok,4.433333,2.627119,12.516667,1.100000,1.533333,41.266667,15.583333,Safe,Unsafe,Unsafe,Unsafe,Safe
pantai lampuuk,3.802817,14.502347,14.915493,2.183099,2.267606,39.180751,15.091549,Safe,Safe,Unsafe,Safe,Safe
pantai lhoknga,1.272198,6.275109,17.983988,2.091703,2.739447,42.742358,17.918486,Unsafe,Safe,Safe,Safe,Safe
pantai samas,2.125000,2.593750,4.968750,1.625000,1.500000,28.937500,6.343750,Safe,Unsafe,Unsafe,Safe,Unsafe
pantai ulee lheue,3.594037,4.446512,19.752294,1.529817,2.922018,48.288991,21.442661,Safe,Unsafe,Safe,Safe,Safe

In [25]:
df_grouped['count'] = (df_grouped == 'Unsafe').sum(axis=1)
max_count = df_grouped['count'].max()

np.int64(3)

In [26]:
df_grouped['Overall Category'] = np.where(df_grouped['count'] >= max_count, 'Unsafe', 'Safe')
df_grouped.drop(columns=['count'], inplace=True)

df_grouped

,Level of Interaction with Disaster,Frequency of Usage (max) (in month),Usage Duration,Number of LIK Combination,Number of Experience with Disaster,Age,Fishing Experience,Level of Interaction with Disaster Status,Frequency of Usage Status,Usage Duration Status,Number of LIK Combination Status,Number of Experience with Disaster Status,Overall Category
Mapped Beach,,,,,,,,,,,,,
pantai depok,4.433333,2.627119,12.516667,1.100000,1.533333,41.266667,15.583333,Safe,Unsafe,Unsafe,Unsafe,Safe,Unsafe
pantai lampuuk,3.802817,14.502347,14.915493,2.183099,2.267606,39.180751,15.091549,Safe,Safe,Unsafe,Safe,Safe,Safe
pantai lhoknga,1.272198,6.275109,17.983988,2.091703,2.739447,42.742358,17.918486,Unsafe,Safe,Safe,Safe,Safe,Safe
pantai samas,2.125000,2.593750,4.968750,1.625000,1.500000,28.937500,6.343750,Safe,Unsafe,Unsafe,Safe,Unsafe,Unsafe
pantai ulee lheue,3.594037,4.446512,19.752294,1.529817,2.922018,48.288991,21.442661,Safe,Unsafe,Safe,Safe,Safe,Safe

In [27]:
# Save the rule matrix
df_grouped.to_csv('data/community_rule_categorization.csv')

In [38]:
df = pd.read_csv('data/community_rule_categorization.csv')

category = df.loc[df['Mapped Beach'] == 'pantai depok', 'Number of Experience with Disaster Status'].iloc[0]
category

'Safe'